### ISSUE TITLE
nn_tools inquiry

### ISSUE THREAD

**Issue by Safiier** [victoriaono/camels#1]
In networks.py line 4,
_from .nn_tools import zero_init_
I'm sorry but where can I find the nn_tools?

**Comment by victoriaono** [comment]
Ah my apologies, I fixed some of my redundant code files because zero_init exists in utils.py (https://github.com/victoriaono/variational-diffusion-cdm/blob/a5c1a9af5bd32bca668b500f94a759dbfb63050e/model/utils/utils.py#L37C1-L37C59). Thank you for flagging!
